cartesian_controller:
  type: "position_controllers/CartesianMotionController"
  end_effector_link: "tool0"
  robot_base_link: "base_link"  #Careful this are urdf parsed frames. So if any sofware solution adds tf_prefixes this leads to errors
  target_frame_topic: "target_pose" #Careful this are urdf parsed frames. So if any sofware solution adds tf_prefixes this leads to errors
  joints:
   - shoulder_pan_joint
   - shoulder_lift_joint
   - elbow_joint
   - wrist_1_joint
   - wrist_2_joint
   - wrist_3_joint


  pd_gains:    
    trans_x: {p: 5.0}
    trans_y: {p: 5.0}
    trans_z: {p: 5.0}
    rot_x: {p: 1.3}
    rot_y: {p: 1.3}
    rot_z: {p: 1.3}